/* jdbc:hsqldb:file:/Users/ehamerski/Documents/workspace-ejb3/database/exemplo-1/exemplo-1 */

drop table if exists clientes
drop table if exists produtos
drop table if exists pedidos
drop table if exists itens

create cached table clientes ( 
	cli_id integer generated by default as identity (start with 1) not null primary key,
	cli_nome varchar(50) not null
)

create cached table produtos ( 
	prd_id integer generated by default as identity (start with 1) not null primary key,
	prd_nome varchar(50) not null
)

create cached table pedidos ( 
	pdd_id integer generated by default as identity (start with 1) not null primary key,
	cli_id_fk integer not null, 
	pdd_data date not null
)

create index pedidos_fk1 on pedidos ( cli_id_fk )
create index pedidos_ak1 on pedidos ( pdd_data  )

create cached table itens ( 
	itn_id integer generated by default as identity (start with 1) not null primary key,
	pdd_id_fk integer not null, 
	prd_id_fk integer not null, 
	itn_qtdd integer not null
)

create index itens_fk1 on itens ( pdd_id_fk )
create index itens_fk2 on itens ( prd_id_fk )

/* constraint */
create unique index itens_uk1 on itens ( pdd_id_fk, prd_id_fk )

insert into clientes (cli_nome) values ('Cliente #1')
insert into clientes (cli_nome) values ('Cliente #2')
insert into clientes (cli_nome) values ('Cliente #3')
insert into clientes (cli_nome) values ('Cliente #4')
insert into clientes (cli_nome) values ('Cliente #5')

insert into produtos (prd_nome) values ('Produto #1')
insert into produtos (prd_nome) values ('Produto #2')
insert into produtos (prd_nome) values ('Produto #3')
insert into produtos (prd_nome) values ('Produto #4')
insert into produtos (prd_nome) values ('Produto #5')

insert into pedidos (cli_id_fk, pdd_data) values ( 1, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 2, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 2, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 3, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 3, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 3, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 4, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 4, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 4, curdate())
insert into pedidos (cli_id_fk, pdd_data) values ( 4, curdate())

insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 1,  1,  1)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 2,  1,  2)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 2,  2,  3)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 3,  1,  4)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 3,  2,  5)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 3,  3,  5)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 4,  1,  4)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 4,  2,  3)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 4,  3,  2)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 4,  4,  1)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 5,  1,  1)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 5,  2,  2)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 5,  3,  3)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 5,  4,  4)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 5,  5,  5)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 6,  1,  5)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 7,  1,  4)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 7,  2,  3)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 8,  1,  2)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 8,  2,  1)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 8,  3,  1)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 9,  1,  2)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 9,  2,  3)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 9,  3,  4)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values ( 9,  4,  5)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values (10,  1,  5)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values (10,  2,  4)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values (10,  3,  3)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values (10,  4,  2)
insert into itens (pdd_id_fk, prd_id_fk, itn_qtdd) values (10,  5,  1)
